version: "3"
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    command: ["sh", "-c", "npm run dev"]

  server:
    build:
      context: ./server
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    command: ["sh", "-c", "npm run dev"]

  mongo:
    image: mongo
    ports:
      - "27017:27017"
