# Use the official Node.js image as the base
FROM node:18.16.1

# Set the working directory inside the container
WORKDIR /app/client

# Copy package.json and package-lock.json (if available)
COPY client/package*.json ./

# Install client dependencies
RUN npm install

# Copy the rest of the client code
COPY client/ .

# Expose the port that the Next.js app will listen on
EXPOSE 3000

# Command to start the Next.js app
CMD ["npm", "run", "dev"]