# Use the official Node.js image as the base
FROM node:18.16.1

# Set the working directory inside the container
WORKDIR /app/server

# Copy package.json and package-lock.json (if available)
COPY server/package*.json ./

# Install server dependencies
RUN npm install

# Copy the rest of the server code
COPY server/ .

# Expose the port that the Node.js server will listen on
EXPOSE 4000

# Command to start the Node.js server
CMD ["npm", "run", "dev"]